server.port=8080
spring.application.name=demo

spring.mongodb.uri=mongodb+srv://asarutheen:itsmemdasar415@cluster0.4k5ig.mongodb.net/jewellerydp?retryWrites=true&w=majority

# JWT secret (change to secure random)
jwt.secret=s7w2$Xt@ALq!415BfZy4KcM!2nA#1L3vX8pdeVYtRdFgAsaRQ
jwt.expirationMs=86400000


# File upload local folder (if using local storage)
file.upload-dir=uploads
app.upload.category=uploads/categories



# Cloudinary Configuration (Use environment variables)
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}